version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: tb_postgres_new  
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ticketblitz
    ports:
      - "5433:5432"  

  redis:
    image: redis:7-alpine
    container_name: tb_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tb_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"